server:
  port: 8889

spring:
  devtools:
    livereload:
      enabled: true
  application:
    name: auth-server
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    database-type: postgresql
    url: jdbc:postgresql://192.168.100.72:5432/pidimeta
    username: pidimeta
    password: pidimeta
    driver-class-name: org.postgresql.Driver
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    mybatis:
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        format_sql: true
    generate-ddl: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
