server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/**

        - id: product
          uri: lb://product
          predicates:
            Path=/products/**
          filters:
            - CustomAuthFilter

        - id: display
          uri: lb://display
          predicates:
            Path=/displays/**
          filters:
            - CustomAuthFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
